name: probclass
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - expat=2.6.4
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pillow=11.0.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.12.8
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing_extensions=4.12.2
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - alabaster==1.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - attrs==24.3.0
      - autorank==1.2.1
      - babel==2.16.0
      - baycomp==1.0.3
      - catboost==1.2.7
      - cffi==1.17.1
      - cir-model==0.2.0
      - click==8.1.8
      - cloudpickle==3.1.0
      - contourpy==1.3.1
      - coverage==7.6.10
      - cycler==0.12.1
      - dask==2024.12.1
      - dask-expr==1.1.21
      - deprecation==2.1.0
      - dill==0.3.9
      - docutils==0.21.2
      - et-xmlfile==2.0.0
      - fire==0.7.0
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gpytorch==1.13
      - grpcio==1.69.0
      - imagesize==1.4.1
      - iniconfig==2.0.0
      - jaxtyping==0.2.19
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - liac-arff==2.5.0
      - lightgbm==4.5.0
      - lightning-utilities==0.11.9
      - linear-operator==0.5.3
      - locket==1.0.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - minio==7.2.14
      - msgpack==1.1.0
      - msgpack-numpy==0.4.8
      - multidict==6.1.0
      - myst-parser==4.0.0
      - netcal==1.3.6
      - numpy==1.26.4
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.24.3
      - openml==0.15.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==2.2.3
      - partd==1.4.2
      - patool==3.1.0
      - patsy==1.0.1
      - plotly==5.24.1
      - pluggy==1.5.0
      - probmetrics==0.0.1
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==6.1.1
      - pyarrow==18.1.0
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pygments==2.19.1
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytabkit==1.1.3
      - pytest==8.3.4
      - pytest-cov==6.0.0
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytorch-lightning==2.5.0.post0
      - pytz==2024.2
      - ray==2.40.0
      - referencing==0.35.1
      - relplot==1.0
      - rpds-py==0.22.3
      - scikit-learn==1.5.2
      - scipy==1.15.1
      - seaborn==0.13.2
      - six==1.17.0
      - skorch==1.1.0
      - snowballstemmer==2.2.0
      - sphinx==8.1.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - statsmodels==0.14.4
      - swig==4.3.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tikzplotlib==0.9.8
      - toolz==1.0.0
      - torchmetrics==1.6.1
      - tqdm==4.67.1
      - tueplots==0.0.17
      - typeguard==4.4.1
      - tzdata==2024.2
      - venn-abers==1.4.6
      - werkzeug==3.1.3
      - xgboost==2.1.3
      - xlrd==2.0.1
      - xmltodict==0.14.2
      - yarl==1.18.3